### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object

### ISSUE THREAD

**Issue by dgilling** [Moesif/moesif-express#2]
code:"E_UNEXPECTED" err_trace:"TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object. at fromObject (buffer.js:287:9) at Function.Buffer.from (buffer.js:133:10) at ServerResponse.res.end (.../moesif-express/lib/index.js:115:31)

**Comment by dgilling** [comment]
Fixed in 2.3.11
